# Generated by Django 4.2b1 on 2023-04-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppKaren', '0002_destino_paquete_viajero_delete_curso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Destino',
        ),
        migrations.RenameField(
            model_name='paquete',
            old_name='nombre',
            new_name='lugar',
        ),
    ]
