# Generated by Django 4.2b1 on 2023-04-09 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppKaren', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paquete',
        ),
        migrations.DeleteModel(
            name='Viajero',
        ),
        migrations.DeleteModel(
            name='Visita',
        ),
    ]
